alias fmb='cd ~/projects/cambridge/MSnbase/'
alias fmq='cd ~/projects/r/MALDIquant/'
alias fmqf='cd ~/projects/r/MALDIquantForeign/'
alias ftr='cd ~/projects/pavel/topdownr/'
alias fp='cd ~/projects/'
alias fr='cd ~/projects/r'
alias fsd='cd ~/projects/sepsisdialog/'
alias fd='cd ~/tmp/downloads/'
